### ISSUE TITLE
Server not found

### ISSUE THREAD

**Issue by Caodongying** [JesperFritsch/snake_server#1]
uvicorn main:app --port 2222  --host 0.0.0.0 can be executed, but the server says "{"detail":"Not Found"}".

<img width="529" alt="image" src="https://github.com/JesperFritsch/snake_server/assets/40957362/bb089016-d280-41f1-9d5f-ca045aa1bce2">

Plus: need to manually create the logs folder, otherwise will get an error "IsADirectoryError: [Errno 21] Is a directory: '/[my path]/snake_server/logs/app.log'".

🤔

**Comment by JesperFritsch** [comment]
Does the server respond that when you run the client_test.py file? check that the uri is correct it should be ws//:localhost:2222/ws for you i think

**Comment by Caodongying** [comment]
Haha it's working!
<img width="1000" alt="image" src="https://github.com/JesperFritsch/snake_server/assets/40957362/2476a132-ccf6-45e9-b8df-0e1d2d1c4c28">

**Comment by JesperFritsch** [comment]
Cool! just so you know, you do not need the server just to run it locally, you can just call snake_sim/main.py with the --stream argument, or the --compute argument so generate a runfile.json and then play the runfile with snake_sim/main.py --play-file argument :)

**Comment by Caodongying** [comment]
Somehow the relative path is not working despite sys.path.append(os.getcwd())🧐. To get the main.py run, I used absolute path instead.

<img width="779" alt="image" src="https://github.com/JesperFritsch/snake_server/assets/40957362/45477c72-1005-440f-9643-eccad2461659">

But then it works! mycket bra!

(And yes I can feel that running with --compute takes a loooong time to finish🤖)

**Comment by JesperFritsch** [comment]
'sys.path.append(os.getcwd())' is really just for python to be able to find the modules that are imported, with a correct .pth it is not needed at all, i should remove it really. If you want the relative path to work you need to make sure that you are located at what/ever/snake_sim/ when you run 'python main.py' the relative path is relative to your current working directory, if you for example are located at /Users/dongying/Desktop/Tech/ and run 'python main.py' then the relative path is relative to '/Users/dongying/Desktop/Tech/' and '/Users/dongying/Desktop/Tech/default_config.json' does not exist :)

**Comment by Caodongying** [comment]
Aha I see! I thought getcwd() returns the file path. I mixed up getcwd() and  os.path.dirname(os.path.abspath(__file__)). Yes you're right, I was not under snake_sim folder.

Genius👍

**Comment by JesperFritsch** [comment]
The current working directory (cwd) is where you are located in the shell or the terminal. So getcwd() will return what ever path you are at when you call python <scipt>.py as long as the script does not change the current working directory during execution:)

**Comment by JesperFritsch** [comment]
__file__ would contain the path to the file being executed.

**Comment by JesperFritsch** [comment]
'__file__' would contain the path to the file being executed.

**Comment by JesperFritsch** [comment]
"__file__" would contain the path to the file being executed.

**Comment by Caodongying** [comment]
Haha very clear now, thank you teacher! These two comments will go to my KnowledgeBase notebook💯

(actually I used to set some absolute path for testing purpose even in framework repo hehe🤡 as I didn't get some relative paths to work. )

**Comment by JesperFritsch** [comment]
We are all learning☺️
